# Generated by Django 6.0 on 2025-12-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
